apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2   #new 
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  name: example-app
  namespace: example-app
spec:
  tls:
  - hosts:
    - marcel.test
    secretName: marcel-tls-secret
  rules:
  - host: marcel.test
    http:
      paths:
      - path: /v1/hello
        pathType: ImplementationSpecific
        backend:
          service:
            name: example-service
            port: 
              number: 80
      - path: /v2/hello
        pathType: ImplementationSpecific
        backend:
          service:
            name: example-service
            port: 
              number: 80
